In [1]:
import torch
x = torch.rand(3, 3)
x


tensor([[0.5309, 0.0573, 0.3816],
        [0.5984, 0.2089, 0.2671],
        [0.1662, 0.7638, 0.9335]])

In [2]:
x.shape


torch.Size([3, 3])

In [3]:
x.dtype


torch.float32

In [4]:
"hello world"

'hello world'

In [5]:
image = torch.tensor([[0.1, 0.2, 0.3],
                      [0.4, 0.5, 0.6],
                      [0.7, 0.8, 0.9]])

In [7]:
w = torch.randn(3, 3, requires_grad=True)

print(f"이미지 데이터:\n{image}")
print(f"무작위 가중치:\n{w}")

이미지 데이터:
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])
무작위 가중치:
tensor([[-1.5847,  0.7170, -0.4689],
        [-0.3916, -1.2323, -0.5785],
        [-0.2338, -0.2675, -1.0700]], requires_grad=True)


In [8]:
z = torch.sum(image * w) + 0.1  # 0.1은 편향(b)입니다.
print(f"판단 전 숫자(z): {z.item()}")

판단 전 숫자(z): -2.516322374343872


In [9]:
a = torch.relu(z)
print(f"활성화 후 값(a): {a.item()}")

활성화 후 값(a): 0.0
